/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "app/**/*.{ts,tsx}", 
    "components/**/*.{ts,tsx}"
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        // Base colors from UnoCSS config
        white: '#FFFFFF',
        gray: {
          50: '#FAFAFA',
          100: '#F5F5F5',
          200: '#E5E5E5',
          300: '#D4D4D4',
          400: '#A3A3A3',
          500: '#737373',
          600: '#525252',
          700: '#404040',
          800: '#262626',
          900: '#171717',
          950: '#0A0A0A',
        },
        accent: {
          50: '#F8F5FF',
          100: '#F0EBFF',
          200: '#E1D6FF',
          300: '#CEBEFF',
          400: '#B69EFF',
          500: '#9C7DFF',
          600: '#8A5FFF',
          700: '#7645E8',
          800: '#6234BB',
          900: '#502D93',
          950: '#2D1959',
        },
        neutral: {
          50: '#FAFAFA',
          100: '#F5F5F5',
          200: '#E5E5E5',
          300: '#D4D4D4',
          400: '#A3A3A3',
          500: '#737373',
          600: '#525252',
          700: '#404040',
          800: '#262626',
          900: '#171717',
          950: '#0A0A0A',
        },
        green: {
          50: '#F0FDF4',
          100: '#DCFCE7',
          200: '#BBF7D0',
          300: '#86EFAC',
          400: '#4ADE80',
          500: '#22C55E',
          600: '#16A34A',
          700: '#15803D',
          800: '#166534',
          900: '#14532D',
          950: '#052E16',
        },
        orange: {
          50: '#FFFAEB',
          100: '#FEEFC7',
          200: '#FEDF89',
          300: '#FEC84B',
          400: '#FDB022',
          500: '#F79009',
          600: '#DC6803',
          700: '#B54708',
          800: '#93370D',
          900: '#792E0D',
        },
        red: {
          50: '#FEF2F2',
          100: '#FEE2E2',
          200: '#FECACA',
          300: '#FCA5A5',
          400: '#F87171',
          500: '#EF4444',
          600: '#DC2626',
          700: '#B91C1C',
          800: '#991B1B',
          900: '#7F1D1D',
          950: '#450A0A',
        },
        // Custom dark theme colors based on #363635d9
        dark: {
          50: '#f8f8f7',
          100: '#e5e5e4',
          200: '#d1d1cf',
          300: '#a8a8a7',
          400: '#7a7a79',
          500: '#5c5c5b',
          600: '#4a4a49',
          700: '#363635',
          800: '#2a2a29',
          900: '#1f1f1e',
          950: '#0f0f0e',
        },
        // shadcn/ui color variables
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        // Bolt specific colors using CSS variables
        bolt: {
          elements: {
            'border-color': 'var(--bolt-elements-borderColor)',
            'border-color-active': 'var(--bolt-elements-borderColorActive)',
            'bg-depth-1': 'var(--bolt-elements-bg-depth-1)',
            'bg-depth-2': 'var(--bolt-elements-bg-depth-2)',
            'bg-depth-3': 'var(--bolt-elements-bg-depth-3)',
            'bg-depth-4': 'var(--bolt-elements-bg-depth-4)',
            'text-primary': 'var(--bolt-elements-textPrimary)',
            'text-secondary': 'var(--bolt-elements-textSecondary)',
            'text-tertiary': 'var(--bolt-elements-textTertiary)',
            'code-background': 'var(--bolt-elements-code-background)',
            'code-text': 'var(--bolt-elements-code-text)',
            'button-primary-background': 'var(--bolt-elements-button-primary-background)',
            'button-primary-background-hover': 'var(--bolt-elements-button-primary-backgroundHover)',
            'button-primary-text': 'var(--bolt-elements-button-primary-text)',
            'button-secondary-background': 'var(--bolt-elements-button-secondary-background)',
            'button-secondary-background-hover': 'var(--bolt-elements-button-secondary-backgroundHover)',
            'button-secondary-text': 'var(--bolt-elements-button-secondary-text)',
            'button-danger-background': 'var(--bolt-elements-button-danger-background)',
            'button-danger-background-hover': 'var(--bolt-elements-button-danger-backgroundHover)',
            'button-danger-text': 'var(--bolt-elements-button-danger-text)',
            'item-content-default': 'var(--bolt-elements-item-contentDefault)',
            'item-content-active': 'var(--bolt-elements-item-contentActive)',
            'item-content-accent': 'var(--bolt-elements-item-contentAccent)',
            'item-content-danger': 'var(--bolt-elements-item-contentDanger)',
            'item-background-default': 'var(--bolt-elements-item-backgroundDefault)',
            'item-background-active': 'var(--bolt-elements-item-backgroundActive)',
            'item-background-accent': 'var(--bolt-elements-item-backgroundAccent)',
            'item-background-danger': 'var(--bolt-elements-item-backgroundDanger)',
            'actions-background': 'var(--bolt-elements-actions-background)',
            'actions-code-background': 'var(--bolt-elements-actions-code-background)',
            'artifacts-background': 'var(--bolt-elements-artifacts-background)',
            'artifacts-background-hover': 'var(--bolt-elements-artifacts-backgroundHover)',
            'artifacts-border-color': 'var(--bolt-elements-artifacts-borderColor)',
            'artifacts-inline-code-background': 'var(--bolt-elements-artifacts-inlineCode-background)',
            'artifacts-inline-code-text': 'var(--bolt-elements-artifacts-inlineCode-text)',
            'messages-background': 'var(--bolt-elements-messages-background)',
            'messages-link-color': 'var(--bolt-elements-messages-linkColor)',
            'messages-code-background': 'var(--bolt-elements-messages-code-background)',
            'messages-inline-code-background': 'var(--bolt-elements-messages-inlineCode-background)',
            'messages-inline-code-text': 'var(--bolt-elements-messages-inlineCode-text)',
            'icon-success': 'var(--bolt-elements-icon-success)',
            'icon-error': 'var(--bolt-elements-icon-error)',
            'icon-primary': 'var(--bolt-elements-icon-primary)',
            'icon-secondary': 'var(--bolt-elements-icon-secondary)',
            'icon-tertiary': 'var(--bolt-elements-icon-tertiary)',
            'preview-address-bar-background': 'var(--bolt-elements-preview-addressBar-background)',
            'preview-address-bar-background-hover': 'var(--bolt-elements-preview-addressBar-backgroundHover)',
            'preview-address-bar-background-active': 'var(--bolt-elements-preview-addressBar-backgroundActive)',
            'preview-address-bar-text': 'var(--bolt-elements-preview-addressBar-text)',
            'preview-address-bar-text-active': 'var(--bolt-elements-preview-addressBar-textActive)',
            'terminals-background': 'var(--bolt-elements-terminals-background)',
            'terminals-button-background': 'var(--bolt-elements-terminals-buttonBackground)',
            'divider-color': 'var(--bolt-elements-dividerColor)',
            'loader-background': 'var(--bolt-elements-loader-background)',
            'loader-progress': 'var(--bolt-elements-loader-progress)',
            'prompt-background': 'var(--bolt-elements-prompt-background)',
            'sidebar-dropdown-shadow': 'var(--bolt-elements-sidebar-dropdownShadow)',
            'sidebar-button-background-default': 'var(--bolt-elements-sidebar-buttonBackgroundDefault)',
            'sidebar-button-background-hover': 'var(--bolt-elements-sidebar-buttonBackgroundHover)',
            'sidebar-button-text': 'var(--bolt-elements-sidebar-buttonText)',
            'cta-background': 'var(--bolt-elements-cta-background)',
            'cta-text': 'var(--bolt-elements-cta-text)',
          },
        },
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
        'header-height': 'var(--header-height)',
        'chat-max-width': 'var(--chat-max-width)',
        'chat-min-width': 'var(--chat-min-width)',
        'workbench-width': 'var(--workbench-width)',
        'workbench-inner-width': 'var(--workbench-inner-width)',
        'workbench-left': 'var(--workbench-left)',
      },
      maxWidth: {
        'chat': 'var(--chat-max-width)',
      },
      minWidth: {
        'chat': 'var(--chat-min-width)',
      },
      width: {
        'workbench': 'var(--workbench-width)',
        'workbench-inner': 'var(--workbench-inner-width)',
      },
      left: {
        'workbench': 'var(--workbench-left)',
      },
      top: {
        'header': 'var(--header-height)',
      },
      transitionTimingFunction: {
        'bolt-ease-cubic-bezier': 'cubic-bezier(0.4,0,0.2,1)',
      },
      // Add custom ease classes
      ease: {
        'bolt-cubic-bezier': 'cubic-bezier(0.4,0,0.2,1)',
      },
      // Add missing spacing utilities
      gap: {
        '1.5': '0.375rem',
        '1-5': '0.375rem',
      },
      padding: {
        '0.5': '0.125rem',
        '1.5': '0.375rem',
        '2.5': '0.625rem',
        '0-5': '0.125rem',
        '1-5': '0.375rem',
        '2-5': '0.625rem',
      },
      margin: {
        '1.5': '0.375rem',
        '1-5': '0.375rem',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'zoom-in-98': {
          '0%': { transform: 'scale(0.98)' },
          '100%': { transform: 'scale(1)' },
        },
        'shimmer': {
          '0%': { 
            'background-position': '-200px 0',
            'opacity': '0.6'
          },
          '50%': {
            'opacity': '1'
          },
          '100%': { 
            'background-position': 'calc(200px + 100%) 0',
            'opacity': '0.6'
          },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.1s ease-out',
        'zoom-in-98': 'zoom-in-98 0.1s ease-out',
        'shimmer': 'shimmer 2s ease-in-out infinite',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    // Plugin for custom utilities
    function({ addUtilities }) {
      addUtilities({
        '.transition-theme': {
          'transition-property': 'background-color, border-color, color',
          'transition-duration': '150ms',
          'transition-timing-function': 'cubic-bezier(0.4,0,0.2,1)',
        },
        '.kdb': {
          'background-color': 'var(--bolt-elements-code-background)',
          'color': 'var(--bolt-elements-code-text)',
          'padding': '0.25rem 0.375rem',
          'border-radius': '0.375rem',
        },
        '.scrollbar-hide': {
          'scrollbar-width': 'none',
          '&::-webkit-scrollbar': {
            display: 'none',
          },
        },
      });
    },
  ],
}; 