export default {
    '/package.json': `
{
    "dependencies": {
        "@nivo/bar": "^0.84.0",
        "@nivo/heatmap": "^0.84.0",
        "@nivo/line": "^0.84.0",
        "@nivo/pie": "^0.84.0",
        "@nivo/scatterplot": "^0.84.0",
        "@radix-ui/react-accordion": "^1.1.2",
        "@radix-ui/react-alert-dialog": "^1.0.5",
        "@radix-ui/react-aspect-ratio": "^1.0.3",
        "@radix-ui/react-avatar": "^1.0.4",
        "@radix-ui/react-checkbox": "^1.0.4",
        "@radix-ui/react-collapsible": "^1.0.3",
        "@radix-ui/react-context-menu": "^2.1.5",
        "@radix-ui/react-dialog": "^1.0.5",
        "@radix-ui/react-dropdown-menu": "^2.0.6",
        "@radix-ui/react-hover-card": "^1.0.7",
        "@radix-ui/react-label": "^2.0.2",
        "@radix-ui/react-menubar": "^1.0.4",
        "@radix-ui/react-navigation-menu": "^1.1.4",
        "@radix-ui/react-popover": "^1.0.7",
        "@radix-ui/react-progress": "^1.0.3",
        "@radix-ui/react-radio-group": "^1.1.3",
        "@radix-ui/react-scroll-area": "^1.0.5",
        "@radix-ui/react-select": "^2.0.0",
        "@radix-ui/react-separator": "^1.0.3",
        "@radix-ui/react-slider": "^1.1.2",
        "@radix-ui/react-slot": "^1.0.2",
        "@radix-ui/react-switch": "^1.0.3",
        "@radix-ui/react-tabs": "^1.0.4",
        "@radix-ui/react-toast": "^1.1.5",
        "@radix-ui/react-toggle": "^1.0.3",
        "@radix-ui/react-toggle-group": "^1.0.4",
        "@radix-ui/react-tooltip": "^1.0.7",
        "class-variance-authority": "^0.7.0",
        "clsx": "^2.0.0",
        "cmdk": "^0.2.0",
        "date-fns": "^3.0.1",
        "embla-carousel-react": "^8.0.0-rc17",
        "lucide-react": "^0.298.0",
        "react": "^18.2.0",
        "react-copy-to-clipboard": "^5.1.0",
        "react-day-picker": "^8.9.1",
        "react-dom": "^18.2.0",
        "react-resizable-panels": "^1.0.5",
        "shiki": "^0.14.7",
        "tailwind-merge": "^2.1.0",
        "tailwindcss-animate": "^1.0.7",
        "vaul": "^0.8.0",
        "react-scripts": "^5.0.0",
        "tailwindcss": "^3.4.1"
    },
    "main": "/src/index.js",
    "devDependencies": {
        "autoprefixer": "^10.4.4",
        "eslint": "8.13.0",
        "eslint-config-airbnb": "^19.0.4",
        "eslint-config-prettier": "^8.5.0",
        "eslint-plugin-prettier": "^4.0.0",
        "gulp": "^4.0.2",
        "gulp-inline-source": "^4.0.0",
        "gulp-rename": "^2.0.0",
        "gulp-replace": "^1.1.3",
        "npm-run-all": "^4.1.5",
        "postcss": "^8.4.12",
        "prettier": "^2.6.2",
        "prettier-plugin-tailwindcss": "^0.1.8"
    }
}
    `
}